# Generated by Django 5.1.5 on 2025-02-14 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='owner',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='owned_car_brand', to='telegram_app.user'),
        ),
        migrations.AddField(
            model_name='carbrand',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='updated_car_brand', to='telegram_app.user'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='owner',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='owned_car_model', to='telegram_app.user'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='updated_car_model', to='telegram_app.user'),
        ),
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='owned_category', to='telegram_app.user'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='updated_category', to='telegram_app.user'),
        ),
    ]
