# Generated by Django 5.1.5 on 2025-02-10 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0003_discount_name_discount_owner_discount_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='owned_discounts', to='telegram_app.user'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_discounts', to='telegram_app.user'),
        ),
    ]
