# Generated by Django 5.1.5 on 2025-02-18 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0003_alter_saveditem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='reward',
        ),
        migrations.AddField(
            model_name='reward',
            name='promocode',
            field=models.OneToOneField(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward', to='telegram_app.promocode'),
        ),
    ]
