# Generated by Django 5.1.5 on 2025-01-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0003_carbrand_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='part_name',
            new_name='name',
        ),
    ]
