# Generated by Django 5.1.5 on 2025-01-25 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0004_rename_part_name_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photos',
            new_name='photo',
        ),
    ]
