# Generated by Django 5.1.5 on 2025-02-11 20:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0004_alter_discount_owner_alter_discount_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discount',
            name='owner',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='owned_discounts', to='telegram_app.user'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
