# Generated by Django 5.1.5 on 2025-02-12 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0005_promocode_created_at_promocode_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_promocodes', to='telegram_app.user'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='updated_promocodes', to='telegram_app.user'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
