# Generated by Django 5.1.5 on 2025-02-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0006_promocode_owner_promocode_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
