# Generated by Django 5.1.5 on 2025-02-01 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0006_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('usage_limit', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.CharField(choices=[('new', 'New'), ('renewed', 'Renewed'), ('excellent', 'Excellent'), ('good', 'Good'), ('acceptable', 'Acceptable')], default='new', max_length=10),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g. 10 for 10%)', max_digits=5)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='telegram_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedPromocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_promocodes', to='telegram_app.cart')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_carts', to='telegram_app.promocode')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_app.promocode'),
        ),
        migrations.DeleteModel(
            name='AppliedDiscount',
        ),
        migrations.DeleteModel(
            name='DiscountCode',
        ),
    ]
