# Generated by Django 5.1.5 on 2025-02-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0007_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='telegram_app.product'),
        ),
    ]
