# Generated by Django 5.1.5 on 2025-02-28 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0009_alter_product_owner_alter_product_updated_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocodehistory',
            options={'verbose_name_plural': 'Promocode History'},
        ),
        migrations.AlterModelOptions(
            name='rewardhistory',
            options={'verbose_name_plural': 'Reward History'},
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_car_brand', to='telegram_app.user'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_car_brand', to='telegram_app.user'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_car_model', to='telegram_app.user'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_car_model', to='telegram_app.user'),
        ),
        migrations.AlterField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_categories', to='telegram_app.user'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_categories', to='telegram_app.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='car_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='telegram_app.carbrand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='telegram_app.carmodel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='telegram_app.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='AppliedPromocode',
        ),
    ]
