# Generated by Django 5.1.5 on 2025-02-13 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0009_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='required_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promocode',
            name='reward',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promocode', to='telegram_app.reward'),
        ),
        migrations.AddField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('free_shipping', 'Free Shipping'), ('gift', 'Gift'), ('promocode', 'Promocode')], default='gift', max_length=20),
        ),
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
