# Generated by Django 5.1.5 on 2025-02-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0011_user_extra_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='state',
            new_name='region',
        ),
    ]
