# Generated by Django 5.1.5 on 2025-03-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0011_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', "Ko'rib chiqilmoqda"), ('approved', 'Joylashtirildi'), ('rejected', 'Rad etilgan')], default='approved', max_length=10),
        ),
    ]
