# Generated by Django 5.1.5 on 2025-03-04 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0012_product_rejection_reason_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedPromocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_promocodes', to='telegram_app.cart')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_carts', to='telegram_app.promocode')),
            ],
        ),
    ]
