# Generated by Django 5.1.5 on 2025-03-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0013_appliedpromocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
