# Generated by Django 5.1.5 on 2025-03-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0016_cart_warning_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='last_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
