# Generated by Django 5.1.5 on 2025-03-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0017_cart_last_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardhistory',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
