# Generated by Django 5.1.5 on 2025-03-15 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0019_user_last_pending_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('technical', 'Texnik yordam'), ('orders', 'Buyurtmalar'), ('general', 'Umumiy savollar')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('claimed', 'Qabul qilingan'), ('answered', 'Javob berilgan'), ('deferred', 'Keyinga qoldirilgan')], default='pending', max_length=10)),
                ('answer', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='question_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['Admin', 'Superadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_questions', to='telegram_app.user')),
                ('deferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_questions', to='telegram_app.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='telegram_app.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
