# Generated by Django 5.1.5 on 2025-03-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0020_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='deferred_by',
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('claimed', "Ko'rib chiqilmoqda"), ('answered', 'Javob berilgan')], default='pending', max_length=10),
        ),
    ]
