# Generated by Django 5.1.5 on 2025-03-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0025_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('pending', "Yig'ilmoqda"), ('claimed', "Ko'rib chiqilmoqda"), ('answered', 'Javob berilgan')], default='pending', max_length=10),
        ),
    ]
