# Generated by Django 5.1.5 on 2025-03-20 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0027_order_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promocode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reward',
        ),
        migrations.AddField(
            model_name='cart',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_app.promocode'),
        ),
        migrations.AddField(
            model_name='cart',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='telegram_app.reward'),
        ),
    ]
