# Generated by Django 5.1.5 on 2025-03-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0028_remove_order_promocode_remove_order_reward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='promocode',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='reward',
        ),
        migrations.AddField(
            model_name='cart',
            name='promocodes',
            field=models.ManyToManyField(blank=True, related_name='used_in_carts', to='telegram_app.promocode'),
        ),
        migrations.AddField(
            model_name='cart',
            name='rewards',
            field=models.ManyToManyField(blank=True, related_name='applied_carts', to='telegram_app.reward'),
        ),
    ]
