# Generated by Django 5.1.5 on 2025-04-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0032_order_city_order_region_order_street_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('claimed', "Ko'rib chiqilmoqda"), ('answered', 'Javob berilgan')], default='pending', max_length=10),
        ),
    ]
